---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  phpmd:
    enabled: false
    config:
      file_extensions: "php"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: false
    config:
      file_extensions: "php,inc"
      standard: ".phpcs/Drupal/ruleset.xml"
      ignore_warnings: true
ratings:
  paths:
  - "./*"
exclude_paths:
- STARTERKIT
